### ISSUE TITLE
I am interested with aranya & arhat

### ISSUE THREAD

**Issue by 6congyao** [arhat-dev/go-pkg#1]
So how could we got connections?

**Comment by jeffreystoke** [comment]
Hi @6congyao , sorry for the late reply, I am planning to open source it again once I have prepared the ci/cd pipelines of this organization, if you would like to know details of aranya/arhat, please feel free to email me via the public email address (dev at arhat.dev)

**Comment by jeffreystoke** [comment]
Closing since no further information provided and you can reach me via email.

Please feel free to reopen it if you think necessary.
